theme = "harbor"
baseurl = "https://cshopmate.com/blog/"
title = "CShopmate"
paginate = 7
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

# Optional
# If you use googleAnalytics, you set top-level options in config.toml to the beginning of the config file like other top-level options.
googleAnalytics = "G-KMNGWNYZJB"
# and disqus too.
disqusShortName = "yourdisqusshortname"

[params.goatcounter]
  domain="stats.domain.com"

[Author]
  name = "Hugo Author"

[outputs]
  section = ["JSON", "HTML"]


